### ISSUE TITLE
Missing "fx" method?

### ISSUE THREAD

**Issue by grifferz** [Humanstate/business-gocardless#14]
After using Business::GoCardless for several years, today for the first time I saw this warning from my GoCardless Pro hook for three of today's payments:

```
Couldn't set fx on Business::GoCardless::Payment: Can't locate object method "fx" via package "Business::GoCardless::Payment" at /opt/cpanm/lib/perl5/Business/GoCardless/Resource.pm line 86.
```

I can't seem to find any information about an 'fx' method in GC's API docs. Do you know anything about this, or is this one for GC support?

These three payments still appear to have been created okay and they are from long-standing customers (so this is new behaviour from people who've been paying this way for a while).

**Comment by leejo** [comment]
GoCardless must have added a new attribute on one of their endpoints. As per the code here: https://github.com/Humanstate/business-gocardless/blob/master/lib/Business/GoCardless/Resource.pm#L79-L90 # it's not a problem, the code is written to warn about it rather than fail. So the fix here is to add the `fx` attribute on whatever object this has been added to in the API.

**Comment by leejo** [comment]
@grifferz - https://developer.gocardless.com/api-reference/#overview-changelog - I will be pushing v0.34 to CPAN shortly
